name = "tiramisu"
version = "7.0.0"
target = "javascript"
description = "A 3D game framework for building performant web games in Gleam"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "tiramisu" }

[documentation]
pages = [
    # Guide
    { title = "Â ", path = "#", source = "" },
    { title = "Guide", path = "guide/index.html", source = "./docs/guide/index.md" },
    { title = "Quickstart", path = "guide/01-quickstart.html", source = "./docs/guide/01-quickstart.md" },
    { title = "State Management", path = "guide/02-state-management.html", source = "./docs/guide/02-state-management.md" },
    { title = "Side Effects", path = "guide/03-side-effects.html", source = "./docs/guide/03-side-effects.md" },
    { title = "Scene Graph", path = "guide/04-scene-graph.html", source = "./docs/guide/04-scene-graph.md" },
    { title = "Physics", path = "guide/05-physics.html", source = "./docs/guide/05-physics.md" },
    { title = "UI with Lustre", path = "guide/06-lustre-integration.html", source = "./docs/guide/06-lustre-integration.md" },
    # Advanced
    { title = "Â ", path = "#", source = "" },
    { title = "Architecture", path = "advanced/architecture.html", source = "./docs/advanced/architecture.md" },
    { title = "Runtime", path = "advanced/runtime.html", source = "./docs/advanced/runtime.md" },
]


[dependencies]
gleam_stdlib = ">= 0.64.0 and < 2.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
vec = ">= 3.0.1 and < 4.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
quaterni = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
savoiardi = { git = "http://github.com/renatillas/savoiardi", ref = "main"}

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"
